#!/usr/bin/env python3
"""postprocess-report.py

Merge agent JSON outputs from the Spring Test Harness pipeline into a single
Markdown + JSON harness report.

Usage:
  python3 postprocess-report.py [--out-dir <dir>] <json_file> [<json_file> ...]

  Each <json_file> must be a JSON object with at minimum:
    { "agentName": "<str>", "status": "ok|partial|failed", ... }

  The script merges all inputs and writes two files in <out-dir>:
    harness-report.md   — human-readable Markdown summary
    harness-report.json — merged machine-readable JSON

  If --out-dir is omitted, output goes to stdout (md first, then a JSON fence).

Stdlib only (json, sys, os, argparse, datetime).
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone


# ---------------------------------------------------------------------------
# Status helpers
# ---------------------------------------------------------------------------
STATUS_RANK = {"ok": 0, "partial": 1, "failed": 2}
STATUS_EMOJI = {"ok": "PASS", "partial": "PARTIAL", "failed": "FAIL"}


def _overall_status(agents):
    """Return the worst status across all agents."""
    worst = "ok"
    for a in agents:
        s = a.get("status", "failed")
        if STATUS_RANK.get(s, 2) > STATUS_RANK.get(worst, 0):
            worst = s
    return worst


# ---------------------------------------------------------------------------
# Markdown rendering
# ---------------------------------------------------------------------------
def _render_markdown(agents, overall, generated_at: str) -> str:
    lines = [
        "# Spring Test Harness — Pipeline Report",
        "",
        f"Generated: {generated_at}  ",
        f"Overall status: **{STATUS_EMOJI.get(overall, overall.upper())}**",
        "",
        "---",
        "",
        "## Agent Summaries",
        "",
    ]

    for a in agents:
        name = a.get("agentName", a.get("agent", "unknown"))
        status = a.get("status", "unknown")
        summary = a.get("summary", "")
        badge = STATUS_EMOJI.get(status, status.upper())

        lines.append(f"### {name} — {badge}")
        if summary:
            lines.append("")
            lines.append(summary)

        # Evidence
        evidence = a.get("evidence", [])
        if evidence:
            lines.append("")
            lines.append("**Evidence:**")
            for e in evidence:
                lines.append(f"- {e}")

        # Warnings
        warnings = a.get("warnings", [])
        if warnings:
            lines.append("")
            lines.append("**Warnings:**")
            for w in warnings:
                lines.append(f"- {w}")

        # Errors
        errors = a.get("errors", [])
        if errors:
            lines.append("")
            lines.append("**Errors:**")
            for e in errors:
                lines.append(f"- {e}")

        # Next actions
        next_actions = a.get("nextActions", [])
        if next_actions:
            lines.append("")
            lines.append("**Next Actions:**")
            for n in next_actions:
                lines.append(f"- {n}")

        lines.append("")

    # Test run summary if present
    test_results = [a for a in agents if "passed" in a or "failed" in a]
    if test_results:
        lines.append("---")
        lines.append("")
        lines.append("## Test Results")
        lines.append("")
        for tr in test_results:
            name = tr.get("agentName", "test-runner")
            passed = tr.get("passed", 0)
            failed_list = tr.get("failed", [])
            lines.append(f"**{name}**: {passed} passed, {len(failed_list)} failed")
            if failed_list:
                lines.append("")
                lines.append("| Test | Type | Message |")
                lines.append("|------|------|---------|")
                for f in failed_list[:50]:  # cap table at 50 rows
                    test = f.get("test", "")
                    ftype = f.get("type", "")
                    msg = f.get("message", "").replace("|", "\\|")[:120]
                    lines.append(f"| `{test}` | {ftype} | {msg} |")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by spring-test-harness postprocess-report.py*")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Merge agent JSON outputs into a harness report."
    )
    parser.add_argument(
        "--out-dir",
        default=None,
        help="Directory to write harness-report.md and harness-report.json. "
             "Defaults to stdout.",
    )
    parser.add_argument(
        "inputs",
        nargs="*",
        help="Agent JSON output files to merge.",
    )
    args = parser.parse_args()

    agents = []
    parse_errors = []

    for path in args.inputs:
        if not os.path.isfile(path):
            parse_errors.append(f"File not found: {path}")
            continue
        try:
            with open(path, "r", encoding="utf-8") as fh:
                data = json.load(fh)
            if isinstance(data, dict):
                agents.append(data)
            elif isinstance(data, list):
                agents.extend(data)
            else:
                parse_errors.append(f"Unexpected JSON type in {path}")
        except (json.JSONDecodeError, OSError) as exc:
            parse_errors.append(f"Cannot read {path}: {exc}")

    if not agents and not args.inputs:
        # Try reading a single JSON array/object from stdin
        try:
            data = json.load(sys.stdin)
            if isinstance(data, list):
                agents = data
            elif isinstance(data, dict):
                agents = [data]
        except (json.JSONDecodeError, OSError):
            pass

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    overall = _overall_status(agents)

    merged_json = {
        "generatedAt": generated_at,
        "overallStatus": overall,
        "agentCount": len(agents),
        "parseErrors": parse_errors,
        "agents": agents,
    }

    md = _render_markdown(agents, overall, generated_at)
    json_str = json.dumps(merged_json, indent=2)

    if args.out_dir:
        os.makedirs(args.out_dir, exist_ok=True)
        md_path = os.path.join(args.out_dir, "harness-report.md")
        json_path = os.path.join(args.out_dir, "harness-report.json")
        with open(md_path, "w", encoding="utf-8") as fh:
            fh.write(md)
        with open(json_path, "w", encoding="utf-8") as fh:
            fh.write(json_str)
        print(f"Report written: {md_path}")
        print(f"Report written: {json_path}")
    else:
        sys.stdout.write(md)
        sys.stdout.write("\n```json\n")
        sys.stdout.write(json_str)
        sys.stdout.write("\n```\n")


if __name__ == "__main__":
    main()
